import type { Metadata } from "next";
import "@/app/globals.css";
import { ToastProvider } from "@/components/ToastProvider";
import { StoreProvider } from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>
        <ToastProvider />
        {children}
      </StoreProvider>
    </>
  );
}
