"use client";
import "@/app/globals.css";
import { DashboardHeader } from "@/components/DashboardHeader";
import { useState } from "react";
import { DashboardSidebar } from "@/components/DashboardSidebar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="min-h-screen w-full bg-background flex">
          <DashboardSidebar
            isOpen={sidebarOpen}
            onClose={() => setSidebarOpen(false)}
            activeItem="Dashboard"
          />
          <div className="flex-1 flex flex-col min-w-0">
            <DashboardHeader />
            <main className="flex-1 p-4 md:p-6 lg:p-8 space-y-6 overflow-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
